OPENAI_API_KEY="YOUR OPENAI_API_KEY"
MONGODB_URI = "YOUR MONGODB ATLAS CONNECTION STRING"
DB_NAME = "YOUR DATABASE"
TRAVEL_COLLECTION_NAME = "YOUR COLLECTION"
ATLAS_VECTOR_SEARCH_INDEX_NAME = "YOUR INDEX NAME as per .env in prep_data folder"